### ISSUE TITLE
location of SGEeasy

### ISSUE THREAD

**Issue by mictadlo** [dpryan79/Misc#2]
Hi,
Where could I find [SGEeasy](https://github.com/dpryan79/Misc/blob/master/MPIIE_internal/SlurmEasy#L6)?

Thank you in advance,

Michal

**Comment by dpryan79** [comment]
I don't think I have a copy of it laying around any more. It was quite similar to the `SlurmEasy` script I linked to in a previous thread but with `qsub` used in place of `sbatch` and some options then changed to match.
